DemoSite/DemoSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mag.urls', namespace='mag')),

]

DemoSite/mag/urls.py
from django.urls import path,include
import django.contrib  
from django.contrib.auth import views as  autview
from . import views
app_name = 'mag'
 
urlpatterns = [
	path('', views.home,name='home'),
	path('signup/', views.signup, name='signup'),
	path('login/', autview.LoginView.as_view(), name='login'),
	path('logout/', views.logout, name='logout'),
#autview.LogoutView.as_view(),  name='logout'),
]

DemoSite/mag/models.py
from django.db import models

# Create your models here.
class Name(models.Model):
    name = models.CharField(max_length=100)

DemoSite/mag/forms.py
from django import forms
from django.http import HttpResponse


class NameForm(forms.Form):

        comm = forms.CharField(label="Тема:", max_length=100)
	#message = forms.CharField(widget=forms.Textarea)
	#sender = forms.EmailField()
	#cc_myself = forms.BooleanField(required=False)
        response = HttpResponse()
        response.write("<p> HACK </p>")

DemoSite/mag/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect
from .forms import NameForm
from django.http import HttpResponse

@login_required
def home(request):
    comment="<h1> My sute </h1>"
    if request.method == 'POST':
        form = NameForm(request.POST)
        comm =request.POST
        comm=dict(comm)
        comm=comm['comment']
        comment=str(comm[0])
    else:
        form = NameForm()

    return render(request, 'mag/home.html', {'form':form,'comment': comment})
def logout(request):
    return render(request, 'registration/logout.html')
def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        form.save()
        username = form.cleaned_data.get('username')
        raw_password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=raw_password)
        login(request, user)
        return render(request, 'mag/home.html')
    else:
        form = UserCreationForm()
    return render(request, 'mag/signup.html', {'form': form})

DemoSite/mag/templates/mag/baseD.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Примерный сайт{% endblock %}</title>
  </head>
  <body>
    <header>
      <h1>Сайт</h1>
      {% if user.is_authenticated %}
        <a href="{% url 'mag:logout' %}">Выйти</a>
      {% else %}
        <a href="{% url 'mag:login' %}">Войти</a> / <a href="{% url 'mag:signup' %}">Зарегистрироватся</a>
      {% endif %}
      <hr>
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>
  </body>
</html>

DemoSite/mag/templates/mag/home.html
{% extends 'mag/baseD.html' %}

{% block content %}
  <h2>Добрый день, {{ user.username }}!</h2>
<p> 

</p>
<p>
Хотите оставить коментарий?
</p>
<form action="" method="post">
    <label for="comment">Комментарий: </label>
    <input id="comment" type="text" name="comment" maxlength="100"value="{{ current_name }}" >
    <input type="submit" value="OK">
</form>
<p>


{{ comment|safe }}

</p>

{% endblock %}

DemoSite/mag/templates/mag/signup.html
{% extends 'mag/baseD.html' %}
{% block content %}
  <h2> Регистрация </h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Зарегистрироватся </button>
  </form>
{% endblock %}